select full_name from users where status ="active";
select email, city from users where city = "Ahmedabad";
select * from users where city = "Surat" or city ="Rajkot";
select user_id, full_name from users where status = "inactive";
select * from users where status="active" and city ="surat";
select * from users where email ="rohan@gmail.com";
select email,city,status from users where email ="rohan@gmail.com";
select * from users where user_id = "104";
select email from users where city ="surat" and status ="active";
select 	full_name,city,status from users where status="active" and city = "Ahmedabad";